version: '3'
services:
    this_jupyter:
        build: docker/jupyter
        ports:
            - "8000:8888"
        volumes:
            - .:/home/jovyan
    this_redis:
       image: redis
       volumes:
           - redis_data:/data
    this_api:
       build: docker/jupyter
       ports:
         - "5000:5000"
       volumes:
           - .:/home/jovyan
       environment:
           - FLASK_APP=main.py
           - FLASK_DEBUG=1
       entrypoint: ["flask","run", "--host=0.0.0.0"]
volumes:
    redis_data:
